public enum EventID
{
  
    NONE,
    PLAYER_DEAD = 1,
    PLAYER_RESPAWN = 2,
    DISABLE_OUTLINE_BIRD = 3,
    BUY_PRODUCT_SUCCESS_FIRST = 4,
    BUY_PRODUCT_SUCCESS = 5,
    CHANGE_LANGUAGE = 6,
    REMOVE_ADS = 7,
    FLY_OUT_RANDOM = 8,
    MINI_GAME_CONNECT_BIRD_EGG = 9,

    ScrollEndChange = 100,
    CHANGE_COIN = 101,
    MOVE_SIGHTING_POINT_BOOSTER = 102,
    SNIPER_BOOSTER = 103,
    CLONE_BALLS_BOOSTER = 104,
    ROCKET_BOOSTER = 105,
    FREEZE = 106,
    FLAMEUP_ITEM = 107,
    FASTBOOM_ITEM = 108,
    TIMEBOOM_ITEM = 109,
    CHANGE_HEART = 110,
    PAUSE = 111,
    STOPPAUSE = 112,
    BOOM_EXPlOSION = 113,
    SHOP_CHECK = 114,

}
